---
- name: Remove any carraige returns in nvm install script (windows + git = carraige returns)
  local_action:
    replace:
      dest: '{{ nvm.install_script }}'
      regexp: '\r'

- name: Set execute mode on nvm install script
  file:
    path: '{{ nvm.install_script }}'
    mode: 0755
  tags:
    - nvm

- name: Install nvm
  command: bash -lc '{{ nvm.install_script }}'
  register: nvm_install_result
  changed_when: nvm_install_result.stdout | search("nvm is already installed") == false
  tags:
    - nvm

- name: Source nvm in ~/.profile
  lineinfile:
    dest: ~/.profile
    line: 'source ~/.nvm/nvm.sh'
    create: yes
  tags:
    - nvm

- name: Install correct node version
  command: bash -lc 'nvm install v{{ nvm.node.version }}'
  register: nvm_install_node_result
  changed_when: nvm_install_node_result.stderr | search("is already installed") == false
  tags:
    - nvm

- name: Check default version
  command: bash -lc 'nvm list'
  register: nvm_list_result
  changed_when: false
  tags:
    - nvm

- name: Set default node version
  command: bash -lc 'nvm alias default v{{ nvm.node.version }}'
  when: nvm_list_result.stdout | search('default -> v{{ nvm.node.version }}') == false
  tags:
    - nvm
